Mesh cube
	Vertices 24
		vert	coord	-1.0 -1.0 0.0
			normal	0.0 0.0 -1.0
			uv	1.0 0.0
		vert	coord	-1.0 1.0 0.0
			normal	0.0 0.0 -1.0
			uv	1.0 1.0
		vert	coord	1.0 1.0 0.0
			normal	0.0 0.0 -1.0
			uv	0.0 1.0
		vert	coord	1.0 -1.0 0.0
			normal	0.0 0.0 -1.0
			uv	0.0 0.0
		vert	coord	-1.0 -1.0 2.0
			normal	0.0 0.0 1.0
			uv	0.0 0.0
		vert	coord	1.0 -1.0 2.0
			normal	0.0 0.0 1.0
			uv	1.0 0.0
		vert	coord	1.0 1.0 2.0
			normal	0.0 0.0 1.0
			uv	1.0 1.0
		vert	coord	-1.0 1.0 2.0
			normal	0.0 0.0 1.0
			uv	0.0 1.0
		vert	coord	-1.0 -1.0 0.0
			normal	0.0 -1.0 0.0
			uv	0.0 0.0
		vert	coord	1.0 -1.0 0.0
			normal	0.0 -1.0 0.0
			uv	1.0 0.0
		vert	coord	1.0 -1.0 2.0
			normal	0.0 -1.0 0.0
			uv	1.0 1.0
		vert	coord	-1.0 -1.0 2.0
			normal	0.0 -1.0 0.0
			uv	0.0 1.0
		vert	coord	1.0 -1.0 0.0
			normal	1.0 0.0 0.0
			uv	0.0 0.0
		vert	coord	1.0 1.0 0.0
			normal	1.0 0.0 0.0
			uv	1.0 0.0
		vert	coord	1.0 1.0 2.0
			normal	1.0 0.0 0.0
			uv	1.0 1.0
		vert	coord	1.0 -1.0 2.0
			normal	1.0 0.0 0.0
			uv	0.0 1.0
		vert	coord	1.0 1.0 0.0
			normal	0.0 1.0 0.0
			uv	0.0 0.0
		vert	coord	-1.0 1.0 0.0
			normal	0.0 1.0 0.0
			uv	1.0 0.0
		vert	coord	-1.0 1.0 2.0
			normal	0.0 1.0 0.0
			uv	1.0 1.0
		vert	coord	1.0 1.0 2.0
			normal	0.0 1.0 0.0
			uv	0.0 1.0
		vert	coord	-1.0 1.0 0.0
			normal	-1.0 0.0 0.0
			uv	0.0 0.0
		vert	coord	-1.0 -1.0 0.0
			normal	-1.0 0.0 0.0
			uv	1.0 0.0
		vert	coord	-1.0 -1.0 2.0
			normal	-1.0 0.0 0.0
			uv	1.0 1.0
		vert	coord	-1.0 1.0 2.0
			normal	-1.0 0.0 0.0
			uv	0.0 1.0
	EndVertices
	Faces 12
		face	3	index	0 1 2
		face	3	index	2 3 0
		face	3	index	4 5 6
		face	3	index	6 7 4
		face	3	index	8 9 10
		face	3	index	10 11 8
		face	3	index	12 13 14
		face	3	index	14 15 12
		face	3	index	16 17 18
		face	3	index	18 19 16
		face	3	index	20 21 22
		face	3	index	22 23 20
	EndFaces
End
